baseurl: "/" # Controls base URL
languageCode: "en-US" # Controls html lang attribute
title: "Datumorphism" # Homepage title and page title suffix
paginate: 12 # Number of posts to show before paginating
theme: "connectome" # to use as default theme

enableRobotsTXT: true # Suggested, it generates a robots.txt
googleAnalytics: "UA-140452515-1" # Optional, add tracking Id for analytics
SectionPagesMenu: "main" # Enable menu system for lazy bloggers


menu:
  main:
    - name: About
      weight: 1
      identifier: about
      url: /about/
  topright:
    - name: Posts
      weight: 1
      identifier: posts
      url: /posts/

taxonomies:
    tag: "tags"
    link: "links"

params:
  theme_variant: "united" # possible value for the theme_variant `cerulean,cosmo,cyborg,darkly,flatly,journal,litera,lumen,lux,materia,minty,pulse,sandstone,simplex,slate,solar,spacelab,superhero,united,yeti`
  description: "Some random notes on intelligence"
  favicon: "/site/favicon.png" # Path to favicon
  logo: "/site/intelligence.png" # logo of the website
  project_indicator: "Notebooks" # This is the menu item for the list of projects and the title of project list page
  splash: "/img/splash/undraw_to_the_moon_v1mv.svg" # This is the splash image for the landing page. The image is shown in the top left of the page.
  powered_by: "love" # Optional, controls name display on footer
  hide_author: false # Optional, set true to hide author name on posts
  images: # Suggested, controls default OpenGraph images controls author name display on meta tag
  github: "datumorphism" # Optional, to display link to github account in menu bar
  twitter: "" # Optional, to display link to twitter account in menu bar
  author: "Lei Ma" # Default author name and the name to be shown in the footer
  editURL: "https://github.com/datumorphism/datumorphism.github.io/edit/master/content/"
  utterances: # comment system: utterances (https://utteranc.es/) parameters
    repo: "datumorphism/comments"  # repo="[ENTER REPO HERE]", the comments will appear as issues in this repository on github.
    term: pathname               # issue-term="pathname"
    theme: github-light          # theme="github-light"


outputFormats:
  data:
    baseName: "data"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true

outputs:
  home:
    - "HTML"
    - "RSS"
    - "data"
